[project]
name = "schemageneration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "openai>=1.109.1",
    "mcp>=1.0.0",
    "httpx>=0.25.0",
    "python-docx>=1.2.0",
    "pypdf2>=3.0.1",
]
